
CREATE TABLE action (
    id bigint NOT NULL,
    count integer NOT NULL,
    type character varying(255),
    recipe_id bigint
);

ALTER TABLE action ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME action_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE cup (
    id bigint NOT NULL,
    count integer NOT NULL,
    date timestamp without time zone,
    name character varying(255),
    status character varying(255),
    recipe_id bigint
);

ALTER TABLE cup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE ingredient_amount (
    id bigint NOT NULL,
    amount integer NOT NULL,
    ingredient character varying(255),
    action_id bigint
);

ALTER TABLE ingredient_amount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingredient_amount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE recipe (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE recipe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME recipe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE remains (
    ingredient character varying(255) NOT NULL,
    remains integer NOT NULL,
    reserved integer NOT NULL
);

ALTER TABLE ONLY action
    ADD CONSTRAINT action_pkey PRIMARY KEY (id);

ALTER TABLE ONLY cup
    ADD CONSTRAINT cup_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ingredient_amount
    ADD CONSTRAINT ingredient_amount_pkey PRIMARY KEY (id);

ALTER TABLE ONLY recipe
    ADD CONSTRAINT recipe_pkey PRIMARY KEY (id);

ALTER TABLE ONLY remains
    ADD CONSTRAINT remains_pkey PRIMARY KEY (ingredient);

ALTER TABLE ONLY cup
    ADD CONSTRAINT cup_unique UNIQUE (date, name, count);

ALTER TABLE ONLY recipe
    ADD CONSTRAINT recipe_unique UNIQUE (name);

ALTER TABLE ONLY cup
    ADD CONSTRAINT cup_fk FOREIGN KEY (recipe_id) REFERENCES recipe(id);

ALTER TABLE ONLY ingredient_amount
    ADD CONSTRAINT ingredient_amount_fk FOREIGN KEY (action_id) REFERENCES action(id);

ALTER TABLE ONLY action
    ADD CONSTRAINT action_fk FOREIGN KEY (recipe_id) REFERENCES recipe(id);
